version: 2
models:
  - name: yellow_trips
    columns:
      - name: pickup_datetime
        tests: [not_null]
      - name: trip_co2_kgs
        tests: [not_null]
  - name: green_trips
    columns:
      - name: pickup_datetime
        tests: [not_null]
      - name: trip_co2_kgs
        tests: [not_null]
